#!/bin/bash
# Credits: @mrismanaziz
# Copyright (C) 2022 Pyro-ManUserbot
#
# This file is a part of < https://github.com/mrismanaziz/PyroMan-Userbot/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/mrismanaziz/PyroMan-Userbot/blob/main/LICENSE/>.
#
# t.me/SharingUserbot & t.me/Lunatic0de

_starter () {
    echo "Downloading source code"
    git clone https://github.com/ArmanGG01/PyroKar-Userbot
    cd PyroKar-Userbot/ && rm -rf .git
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "PyoKar-Userbot v0.2.0, Copyright © 2022 (Arman) <https://github.com/ArmanGG01>"
    python3 -m PyroKar
}

_starter
